-- rename-webstudio-pages.sql
-- Script to rename existing webstudio_pages table to cms_pages, ensuring
-- all related indexes, constraints, triggers, and sequence names are updated.

-- Drop any existing relation named cms_pages to avoid conflicts
DROP VIEW IF EXISTS public.cms_pages CASCADE;
DROP TABLE IF EXISTS public.cms_pages CASCADE;

-- Rename the table
ALTER TABLE public.webstudio_pages RENAME TO cms_pages;

-- Rename sequence for the id column (if generated by serial)
ALTER SEQUENCE IF EXISTS public.webstudio_pages_id_seq RENAME TO cms_pages_id_seq;
ALTER TABLE cms_pages ALTER COLUMN id SET DEFAULT nextval('cms_pages_id_seq');

-- Rename indexes
ALTER INDEX IF EXISTS idx_webstudio_pages_slug       RENAME TO idx_cms_pages_slug;
ALTER INDEX IF EXISTS idx_webstudio_pages_estado     RENAME TO idx_cms_pages_estado;
ALTER INDEX IF EXISTS idx_webstudio_pages_tipo       RENAME TO idx_cms_pages_tipo;
ALTER INDEX IF EXISTS idx_webstudio_pages_tenant_id  RENAME TO idx_cms_pages_tenant_id;

-- Rename constraints
ALTER TABLE cms_pages RENAME CONSTRAINT webstudio_pages_pkey TO cms_pages_pkey;
ALTER TABLE cms_pages RENAME CONSTRAINT webstudio_pages_slug_key TO cms_pages_slug_key;
ALTER TABLE cms_pages RENAME CONSTRAINT webstudio_pages_tenant_id_fkey TO cms_pages_tenant_id_fkey;

-- Rename trigger
ALTER TRIGGER update_webstudio_pages_updated_at ON cms_pages RENAME TO update_cms_pages_updated_at;

-- Sync sequence to 110 to avoid duplicate primary keys
SELECT setval('cms_pages_id_seq', 110);
