-- SQL schema for the `cms_pages` table used by the store CMS.
-- Stores page widgets in a JSONB column and provides two default pages
-- (`home` and `events`) so the application has something to fetch.

CREATE TABLE IF NOT EXISTS cms_pages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text UNIQUE NOT NULL,
    widgets jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- Default pages expected by the React app
INSERT INTO cms_pages (id, nombre, widgets)
VALUES
    (1, 'home', '{"header":[],"content":[],"footer":[]}'::jsonb),
    (2, 'events', '{"header":[],"content":[],"footer":[]}'::jsonb)
ON CONFLICT DO NOTHING;
