-- SQL schema for the `seats` table used to manage seat availability.
-- Seats are duplicated per function so the same seating map can be reused.
-- The `_id` column corresponds to the identifier generated in the map editor.
-- A unique constraint on `(funcion_id, _id)` prevents inserting the same seat
-- twice for a single function and helps avoid selling the same seat more than once.

CREATE TABLE IF NOT EXISTS seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    _id uuid NOT NULL,
    funcion_id integer NOT NULL REFERENCES funciones(id) ON DELETE CASCADE,
    zona uuid NULL REFERENCES zonas(id),
    status text NOT NULL DEFAULT 'disponible',
    bloqueado boolean NOT NULL DEFAULT false,
    reserved boolean NOT NULL DEFAULT false,
    reserved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE (funcion_id, _id)
);

CREATE INDEX IF NOT EXISTS idx_seats_funcion ON seats(funcion_id);
CREATE INDEX IF NOT EXISTS idx_seats_status ON seats(status);
